[versions]
kotlinx-browser = "0.5.0"
vulkan-kotlin = "1.4.328-1"

[libraries]
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinx-browser" }
vulkan-kotlin = { module = "io.technoirlab.vulkan:vulkan-kotlin", version.ref = "vulkan-kotlin" }
